src/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.home, name='homepage'),
]

src/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('homepage.urls')),
    path('', include('friends.urls')),
    path('', include('games.urls')),
]

handler404 = 'homepage.views.handling_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block title %}
        {% endblock title %}
    </title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="{% static 'css/sb-admin-2.min.css' %}">

    {% block meta %}
    {% endblock meta %}

    {% block link %}
    {% endblock link %}

    {% block styles %}
    {% endblock styles %}
</head>

<!-- Change tag params if necessary -->
<body {% block body_params %}id="page-top"{% endblock body_params %}>
    {% block body %}
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Navbar -->
                {% include 'layout/navbar.html' %}
                <!-- End of Navbar -->

                <!-- Messages -->
                {% if messages %}
                    <div class="messages" style="list-style-type:none;">
                        {% for message in messages %}
                            <li{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">{{ message }}</li>
                        {% endfor %}
                    </div>
                {% endif %}
                <!-- End of Messages -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="card shadow mb-4 col-lg-10 mx-auto">
                        <div class="card-body">
                            <!-- Page Heading -->
                            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                                <h1 class="h3 mb-0 text-gray-800">
                                    {% block page_heading %}
                                    {% endblock page_heading %}
                                </h1>
                            </div>

                            <!-- Content Row -->
                            <div class="row">
                                {% block content %}
                                {% endblock content %}
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End of Page Content -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            {% include 'layout/footer.html' %}
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    {% endblock body %}

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js'%} "></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js'%}"></script>

    {% block script %}
    {% endblock script %}
</body>

</html>

src/templates/layout/footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; BoardQuest 2023</span>
        </div>
    </div>
</footer>

src/templates/layout/navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-primary topbar mb-4 static-top shadow">
    <a class="navbar-brand text-white" href="{% url 'homepage:homepage' %}">BoardQuest</a>

    <div class="collapse navbar-collapse">

        <!-- Topbar Navbar -->
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                    Friends
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'friends:list' user.id %}">My friends</a>
                    <a class="dropdown-item" href="{% url 'friends:search' %}">Search</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'friends:invitations:received' %}">Received invites</a>
                    <a class="dropdown-item" href="{% url 'friends:invitations:sent' %}">Sent invites</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                    Games
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'games:collection' user.id %}">My collection</a>
                    <a class="dropdown-item" href="{% url 'games:supported_games' %}">Browse games</a>
                    <a class="dropdown-item" href="{% url 'games:unsupported_games' %}">Request new games</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">My sessions</a>  <!-- TODO -->
                    <a class="dropdown-item" href="#">New session</a>  <!-- TODO -->
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'users:settings:general' %}">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Achievements</a>  <!-- TODO -->
                    <a class="dropdown-item" href="#">Rankings</a>  <!-- TODO -->
                </div>
            </li>
                {% if groups.moderators.name in user_groups or groups.administrators.name in user_groups %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                        Manage
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'games:requested_games' %}">Requested games</a>
                        <a class="dropdown-item" href="{% url 'games:accepted_games' %}">Accepted games</a>
                    </div>
                </li>
                {% endif %}
            {% endif %}
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <!-- Nav Item - Alerts --> <!-- #TODO alerts -->

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-white">{{ user.username }}</span>
                        <img class="img-profile rounded-circle" src="{{ user.profile.image.url|default:'/media/profile_pics/default.jpg' }}">
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                        aria-labelledby="userDropdown">
                        <!-- Profile -->
                        <a class="dropdown-item" href="{% url 'users:profile' user.id %}">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                            Profile
                        </a>
                        <a class="dropdown-item" href="{% url 'users:settings:general' %}">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                            Settings
                        </a>
                        <!-- Logout. Note: logout link in modal -->
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Logout
                        </a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item mx-1">
                    <a href="{% url 'users:login' %}" class="btn btn-primary btn-user btn-rounded">
                        Login
                    </a>
                </li>
                <li class="nav-item mx-1">
                    <a href="{% url 'users:register' %}" class="btn btn-primary btn-user btn-block">
                        Register
                    </a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>


{% if user.is_authenticated %}

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="logout_modal">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <form id="logout-form" method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endif %}

src/templates/layout/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'homepage' %}">
        <div class="sidebar-brand-icon rotate-n-15"> <!-- #TODO logo -->
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">BoardQuest</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Components</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Components:</h6>
                <a class="collapse-item" href="buttons.html">Buttons</a>
                <a class="collapse-item" href="cards.html">Cards</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="base.html">Blank Page</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>